name: periun
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - asttokens=3.0.0=pyhd8ed1ab_1
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.1.31=hbcca054_0
  - comm=0.2.2=pyhd8ed1ab_1
  - decorator=5.2.1=pyhd8ed1ab_0
  - entrypoints=0.4=pyhd8ed1ab_1
  - exceptiongroup=1.2.2=pyhd8ed1ab_1
  - executing=2.1.0=pyhd8ed1ab_1
  - ipykernel=6.29.5=pyh3099207_0
  - ipython=8.34.0=pyh907856f_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - jupyter_client=7.3.4=pyhd8ed1ab_0
  - jupyter_core=5.7.2=pyh31011fe_1
  - ld_impl_linux-64=2.40=h12ee557_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libsodium=1.0.18=h36c2ea0_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - matplotlib-inline=0.1.7=pyhd8ed1ab_1
  - ncurses=6.4=h6a678d5_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - openssl=3.0.16=h5eee18b_0
  - packaging=24.2=pyhd8ed1ab_2
  - parso=0.8.4=pyhd8ed1ab_1
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - platformdirs=4.3.6=pyhd8ed1ab_1
  - prompt-toolkit=3.0.50=pyha770c72_0
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pygments=2.19.1=pyhd8ed1ab_0
  - python=3.10.16=he870216_1
  - python-dateutil=2.9.0.post0=pyhff2d567_1
  - python_abi=3.10=2_cp310
  - readline=8.2=h5eee18b_0
  - six=1.17.0=pyhd8ed1ab_0
  - sqlite=3.45.3=h5eee18b_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - tk=8.6.14=h39e8969_0
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing_extensions=4.12.2=pyha770c72_1
  - wcwidth=0.2.13=pyhd8ed1ab_1
  - xz=5.6.4=h5eee18b_1
  - zeromq=4.3.5=h6a678d5_0
  - zlib=1.2.13=h5eee18b_1
  - pip:
    - aiohappyeyeballs==2.4.6
    - aiohttp==3.11.13
    - aiosignal==1.3.2
    - annotated-types==0.7.0
    - async-timeout==5.0.1
    - attrs==25.1.0
    - certifi==2025.1.31
    - charset-normalizer==3.4.1
    - click==8.1.8
    - contourpy==1.3.1
    - cycler==0.12.1
    - datasets==3.3.2
    - debugpy==1.8.11
    - dill==0.3.8
    - docker-pycreds==0.4.0
    - filelock==3.13.1
    - fonttools==4.56.0
    - frozenlist==1.5.0
    - fsspec==2024.6.1
    - gitdb==4.0.12
    - gitpython==3.1.44
    - huggingface-hub==0.29.1
    - idna==3.10
    - ipywidgets==8.1.6
    - jinja2==3.1.4
    - joblib==1.4.2
    - jupyterlab-widgets==3.0.14
    - kiwisolver==1.4.8
    - lightning-utilities==0.14.3
    - markdown-it-py==3.0.0
    - markupsafe==2.1.5
    - matplotlib==3.10.1
    - mdurl==0.1.2
    - mpmath==1.3.0
    - multidict==6.1.0
    - multiprocess==0.70.16
    - networkx==3.3
    - numpy==2.1.2
    - nvidia-cublas-cu12==12.1.3.1
    - nvidia-cuda-cupti-cu12==12.1.105
    - nvidia-cuda-nvrtc-cu12==12.1.105
    - nvidia-cuda-runtime-cu12==12.1.105
    - nvidia-cudnn-cu12==9.1.0.70
    - nvidia-cufft-cu12==11.0.2.54
    - nvidia-curand-cu12==10.3.2.106
    - nvidia-cusolver-cu12==11.4.5.107
    - nvidia-cusparse-cu12==12.1.0.106
    - nvidia-nccl-cu12==2.21.5
    - nvidia-nvjitlink-cu12==12.1.105
    - nvidia-nvtx-cu12==12.1.105
    - pandas==2.2.3
    - patsy==1.0.1
    - pillow==11.0.0
    - pip==25.0
    - propcache==0.3.0
    - protobuf==5.29.3
    - psutil==7.0.0
    - pyarrow==19.0.1
    - pydantic==2.10.6
    - pydantic-core==2.27.2
    - pyparsing==3.2.1
    - pytz==2025.1
    - pyyaml==6.0.2
    - pyzmq==26.2.0
    - requests==2.32.3
    - rich==13.9.4
    - safetensors==0.5.3
    - scikit-learn==1.6.1
    - scipy==1.15.2
    - seaborn==0.13.2
    - sentry-sdk==2.22.0
    - setproctitle==1.3.5
    - setuptools==75.8.0
    - smmap==5.0.2
    - statsmodels==0.14.4
    - sympy==1.13.1
    - threadpoolctl==3.5.0
    - timm==1.0.17
    - torch==2.5.1+cu121
    - torchaudio==2.5.1+cu121
    - torchmetrics==1.7.4
    - torchvision==0.20.1+cu121
    - tornado==6.1
    - tqdm==4.67.1
    - triton==3.1.0
    - tzdata==2025.1
    - urllib3==2.3.0
    - wandb==0.19.7
    - wheel==0.45.1
    - widgetsnbextension==4.0.14
    - xxhash==3.5.0
    - yarl==1.18.3
prefix: /anaconda3/envs/periun
